services:
  frontend:
    container_name: crm-frontend-${CONFIG_NAME}
    image: ${DOCKERHUB_USERNAME}/crm-frontend:${TAG}
    ports:
      - "${PORT}:80"
    restart: always
    networks:
      - crm_network

networks:
  crm_network:
    external: true
